config:
  locks: false
  install_tree:
    root: $spack\opt\spack
    projections:
      all: '{architecture}\\{compiler.name}-{compiler.version}\\{name}-{version}-{hash}'
  build_stage:
    - ~/.spack/stage
