packages:
  #all:
    # CI should never build develop/main/master versions of
    # packages.
    # Current issues:
    # - e4s/dav
    #   - hdf5-vol-async => argobot@main
    # - aws-ahug-*
    #   - snap
    #   - tycho2
    #   - amg2013
    #   - cosp2
    #   - snbone
    #   - vpfft
    #   - vpic
    # - aws-isc-aarch64
    #   - sse2neon
    #require: "@:999999999"
  python:
    # This is redundant after https://github.com/spack/spack/pull/33898
    # but specified to allow the existance of a package.yaml for CI configs
    require: "@3.7:"

